name = "tiempos-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
AUCORSA_BASE_URL = "https://aucorsa.es"
AUCORSA_API_BASE_URL = "https://lightapi.aucorsa.es"
CACHE_TTL_MS = "15000"